upscale_factor: 2
log: True
Dataset:
  train_path : ../train
  test_path : ../eval
  image_size: 64
  jitter_val: 0.2
  interpolation: bilinear
  batch_size: 4
  shuffle: True
  drop_last: True
  pin_memory: False
Model:
  layers: 10
  residual: False
Train:
  lr: 1.0e-2
  save_iterval: 200
  number_of_epochs: 1000
  save_dir: ../models
  log_dir: ../runs/lr1e-2
Eval:
  interpolation: bicubic
  save_dir: ../best_models